services:
  yt-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: yt-monitor:latest
    container_name: yt-monitor
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    shm_size: "1gb"
